# The configuration you want to run

# Location of java in the JRE (the default)
#JAVA_HOME=/usr/lib/jvm/jre
# Use the following for location of java in the SDK
#JAVA_HOME=/usr/lib/jvm/java


# Configure the suspend timeout. By default, the suspend timeout is disabled, meaning that the server will not wait
# in the SUSPENDING state for any in-flight requests. This property configures the maximum number of seconds to wait for
# in-flight requests to complete. A value of -1 means the server will wait indefinitely.
#
# Note that increasing this value will extend the time the service unit takes to shut down the server.
# If JBOSS_EAP_SUSPEND_TIMEOUT is configured, ensure that the TimeoutStopSec directive in the systemd service unit
# is set to a value that allows the server to wait until the suspend timeout expires and the server is stopped.
#JBOSS_EAP_SUSPEND_TIMEOUT=300

# Location of the server standard out, e.g /opt/eap/standalone/log/service-console.log
#JBOSS_EAP_CONSOLE_LOG="/opt/eap/standalone/log/service-console.log"

# Define the script to use to start JBoss EAP
#JBOSS_EAP_SH="/opt/eap/bin/domain.sh"

# Define server configuration to start, eg. domain.xml
#JBOSS_EAP_SERVER_CONFIG=domain.xml

# Define the host controller configuration, eg. host.xml
#JBOSS_EAP_HOST_CONFIG=host.xml

# The address to bind to
#JBOSS_EAP_BIND=0.0.0.0

# Additional server args to include on startup
# For example, to add two properties to the server:
#JBOSS_EAP_OPTS="-Dproperty1=value1 -Dproperty2=value2"

# Enables debug traces for the server launch script used by the systemd service unit
#JBOSS_EAP_SYSTEMD_DEBUG=true